variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip
    - .venv/

stages:
  - check
  - build

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv .venv
  - source .venv/bin/activate

black:
  stage: check
  image: python:3.7
  script:
    - pip install black
    - black --check --diff .

flake8:
  stage: check
  image: python:3.7
  script:
    - pip install flake8
    - flake8 .

mypy:
  stage: check
  image: python:3.7
  script:
    - pip install mypy
    - mypy --show-error-context --show-column-numbers .

nix-dry:
  stage: check
  image: nixos/nix:2.3
  script:
    - nix-build -v -v --dry-run ./release.nix --attr library
    - nix-build -v -v --dry-run ./release.nix --attr application
    - nix-build -v -v --dry-run ./release.nix --attr docker

nix:
  stage: build
  image: nixos/nix:2.3
  script:
    - nix-build ./release.nix --attr library
    - nix-build ./release.nix --attr application
    - nix-build ./release.nix --attr docker
  only:
    - master
