variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - check
  - build

black:
  stage: check
  image: nixos/nix:2.3
  script:
    - nix-shell --packages python3Packages.black --run 'black --check --diff .'

flake8:
  stage: check
  image: nixos/nix:2.3
  script:
    - nix-shell --packages python3Packages.flake8 --run 'flake8 .'

mypy:
  stage: check
  image: nixos/nix:2.3
  script:
    - nix-shell --packages python3Packages.mypy --run 'mypy --show-error-context --show-column-numbers .'

nix-dry:
  stage: check
  image: nixos/nix:2.3
  script:
    - nix-build -v -v --dry-run ./release.nix --attr library
    - nix-build -v -v --dry-run ./release.nix --attr application
    - nix-build -v -v --dry-run ./release.nix --attr docker

nix:
  stage: build
  image: nixos/nix:2.3
  script:
    - nix-build ./release.nix --attr library
    - nix-build ./release.nix --attr application
    - nix-build ./release.nix --attr docker
  only:
    - master
